name: flutter_qiblah_example
description: Demonstrates how to use the flutter_qiblah plugin.
publish_to: "https://pub.dev/packages/flutter_qiblah"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_qiblah:
    path: ../

  flutter_svg: ^2.0.9
  google_maps_flutter: ^2.5.3

  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/